In [101]:
import pandas as pd
import numpy as np

In [102]:
df = pd.read_csv("https://raw.githubusercontent.com/AshishRastogi123/Student_Performance_Prediction/main/Student_performance.csv")

In [103]:
df

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,student_performance
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.300,Excellent
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.700,Poor
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.000,Excellent
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.900,Good
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.000,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,18,female,b.tech,4.86,70.7,yes,4.1,good,mixed,high,moderate,69.500,Good
629996,629996,21,female,ba,7.08,54.4,yes,4.5,average,mixed,low,moderate,78.900,Excellent
629997,629997,24,male,bca,0.64,44.2,yes,4.3,poor,online videos,low,moderate,19.599,Poor
629998,629998,20,male,b.com,1.54,75.1,yes,8.2,average,group study,high,moderate,59.100,Average
629999,629999,18,other,b.tech,3.94,75.3,yes,5.8,poor,online videos,low,easy,37.200,Poor

In [104]:
df.columns

Index(['id', 'age', 'gender', 'course', 'study_hours', 'class_attendance',
       'internet_access', 'sleep_hours', 'sleep_quality', 'study_method',
       'facility_rating', 'exam_difficulty', 'exam_score',
       'student_performance'],
      dtype='object')

In [105]:
from sklearn.preprocessing import LabelEncoder

In [106]:
le=LabelEncoder()

TASK 1: Data Information aur Basic Stats **Check**

In [107]:
"""
📌 TASK 1.1: Data Information aur Basic Statistics Check
-----------------------------------------------------------
KYA: Dataset ki basic information dekh rahe hain
KYUN: Ye check karne ke liye ki:
      - Kitne rows aur columns hain
      - Kaunsa column kis type ka hai (number/text)
      - Koi missing value to nahi
      - Data ki range kya hai (min, max, average)
KAUNSA KAAM: Data Understanding (Pehla step)
"""

print("="*50)
print("📊 DATA INFORMATION")
print("="*50)

# Check data types and missing values
df.info()

print("\n" + "="*50)
print("📈 BASIC STATISTICS (Numerical Columns)")
print("="*50)
df.describe()

print("\n" + "="*50)
print("❓ MISSING VALUES CHECK")
print("="*50)
df.isnull().sum()

==================================================
📊 DATA INFORMATION
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   630000 non-null  int64
 1   age                  630000 non-null  int64
 2   gender               630000 non-null  object
 3   course               630000 non-null  object
 4   study_hours          630000 non-null  float64
 5   class_attendance     630000 non-null  float64
 6   internet_access      630000 non-null  object
 7   sleep_hours          630000 non-null  float64
 8   sleep_quality        630000 non-null  object
 9   study_method         630000 non-null  object
 10  facility_rating      630000 non-null  object
 11  exam_difficulty      630000 non-null  object
 12  exam_score           630000 non-null  float64
 13  student_performance  630000 non-null  object
dtypes: float64(4), int64(2), object(8)
memory usage: 67.3+ MB

==================================================
📈 BASIC STATISTICS (Numerical Columns)
==================================================

==================================================
❓ MISSING VALUES CHECK
==================================================

id                     0
age                    0
gender                 0
course                 0
study_hours            0
class_attendance       0
internet_access        0
sleep_hours            0
sleep_quality          0
study_method           0
facility_rating        0
exam_difficulty        0
exam_score             0
student_performance    0
dtype: int64

In [108]:
"""
📌 TASK 1.3: ID Column Remove karna
-----------------------------------------------------------
KYA: 'id' column ko hata rahe hain
KYUN: ID column se koi prediction nahi hoti, ye sirf unique identifier hai
      Model training mein iski koi zaroorat nahi
KAUNSA KAAM: Feature Selection (Unnecessary columns hata rahe hain)
"""

print("="*50)
print("🆔 ID COLUMN REMOVAL")
print("="*50)

if 'id' in df.columns:
    df = df.drop('id', axis=1)
    print("✅ 'id' column removed successfully")

    # Check kitne columns bache
    print(f"\n📌 Columns now: {list(df.columns)}")
    print(f"📊 Total columns: {len(df.columns)}")
else:
    print("ℹ️ 'id' column already removed")
    print(f"\n📌 Current columns: {list(df.columns)}")

# Dataset ka size check
print(f"\n📈 Final dataset size: {len(df)} rows × {len(df.columns)} columns")

==================================================
🆔 ID COLUMN REMOVAL
==================================================
✅ 'id' column removed successfully

📌 Columns now: ['age', 'gender', 'course', 'study_hours', 'class_attendance', 'internet_access', 'sleep_hours', 'sleep_quality', 'study_method', 'facility_rating', 'exam_difficulty', 'exam_score', 'student_performance']
📊 Total columns: 13

📈 Final dataset size: 630000 rows × 13 columns

In [109]:
"""
📌 TASK 1.2: Duplicate Rows Check aur Remove
-----------------------------------------------------------
KYA: Duplicate (ek jaisi) rows check kar rahe hain
KYUN: Machine learning ke liye duplicate data galat results de sakta hai
      Isliye duplicate rows ko remove karna zaroori hai
KAUNSA KAAM: Data Cleaning
"""

print("="*50)
print("🔄 DUPLICATE ROWS CHECK")
print("="*50)

duplicates = df.duplicated().sum()
print(f"Total duplicate rows: {duplicates}")

if duplicates > 0:
    df = df.drop_duplicates()
    print(f"✅ After removing duplicates: {len(df)} rows remain")

    # Check kitne rows hata diye
    removed = 630000 - len(df)
    print(f"🗑️ Removed {removed} duplicate rows")
else:
    print("✅ No duplicate rows found")

print(f"\n📊 Current dataset size: {len(df)} rows")

==================================================
🔄 DUPLICATE ROWS CHECK
==================================================
Total duplicate rows: 0
✅ No duplicate rows found

📊 Current dataset size: 630000 rows

In [110]:
df

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,student_performance
0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.300,Excellent
1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.700,Poor
2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.000,Excellent
3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.900,Good
4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.000,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,18,female,b.tech,4.86,70.7,yes,4.1,good,mixed,high,moderate,69.500,Good
629996,21,female,ba,7.08,54.4,yes,4.5,average,mixed,low,moderate,78.900,Excellent
629997,24,male,bca,0.64,44.2,yes,4.3,poor,online videos,low,moderate,19.599,Poor
629998,20,male,b.com,1.54,75.1,yes,8.2,average,group study,high,moderate,59.100,Average
629999,18,other,b.tech,3.94,75.3,yes,5.8,poor,online videos,low,easy,37.200,Poor

In [111]:
"""
📌 TASK 1.4: Column Types Identify karna
-----------------------------------------------------------
KYA: Kaunse columns categorical (text) hain aur kaunse numerical (numbers)
KYUN: Encoding ke liye pata hona chahiye ki kaunse columns ko convert karna hai
      Categorical columns ko machine readable banana padta hai
KAUNSA KAAM: Data Preparation (Encoding ke liye ready hona)
"""

print("="*50)
print("🔤 CATEGORICAL & NUMERICAL COLUMNS IDENTIFICATION")
print("="*50)

# Categorical columns (object type)
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

# Numerical columns (int64, float64 type)
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("\n📝 CATEGORICAL COLUMNS (Need Encoding):")
print("-" * 40)
for i, col in enumerate(categorical_cols, 1):
    unique_values = df[col].nunique()
    print(f"{i}. {col} - {unique_values} unique values")

print("\n🔢 NUMERICAL COLUMNS (Already numbers):")
print("-" * 40)
for i, col in enumerate(numerical_cols, 1):
    print(f"{i}. {col}")

print("\n" + "="*50)
print(f"✅ Total Categorical Columns: {len(categorical_cols)} (Need Encoding)")
print(f"✅ Total Numerical Columns: {len(numerical_cols)} (Ready for model)")
print(f"📊 Total Columns: {len(df.columns)}")

# Show sample data for categorical columns
print("\n" + "="*50)
print("📋 SAMPLE DATA - First 3 rows of categorical columns:")
print("="*50)
print(df[categorical_cols].head(3))

==================================================
🔤 CATEGORICAL & NUMERICAL COLUMNS IDENTIFICATION
==================================================

📝 CATEGORICAL COLUMNS (Need Encoding):
----------------------------------------
1. gender - 3 unique values
2. course - 7 unique values
3. internet_access - 2 unique values
4. sleep_quality - 3 unique values
5. study_method - 5 unique values
6. facility_rating - 3 unique values
7. exam_difficulty - 3 unique values
8. student_performance - 4 unique values

🔢 NUMERICAL COLUMNS (Already numbers):
----------------------------------------
1. age
2. study_hours
3. class_attendance
4. sleep_hours
5. exam_score

==================================================
✅ Total Categorical Columns: 8 (Need Encoding)
✅ Total Numerical Columns: 5 (Ready for model)
📊 Total Columns: 13

==================================================
📋 SAMPLE DATA - First 3 rows of categorical columns:
==================================================
   gender   course internet_access sleep_quality   study_method  \
0  female     b.sc              no       average  online videos
1   other  diploma             yes          poor     self-study
2  female     b.sc             yes          poor       coaching

  facility_rating exam_difficulty student_performance
0             low            easy           Excellent
1          medium        moderate                Poor
2            high        moderate           Excellent

TASK 2 START: ENCODING CATEGORICAL VARIABLES
Ab hum Encoding karenge. Pehle decide karte hain kaunsa encoding kahan use karna hai:

Encoding Strategy:
Label Encoding - Jahan 2-3 unique values hain (ordered categories)

One-Hot Encoding - Jahan 4+ unique values hain (no order)

In [112]:
"""
📌 TASK 2.1: Label Encoding
-----------------------------------------------------------
KYA: Categorical columns ko numbers mein convert kar rahe hain
      (gender, internet_access, sleep_quality, facility_rating, exam_difficulty)
KYUN: Machine learning models sirf numbers samajhte hain, text nahi
KAUNSA KAAM: Feature Encoding (Pehla encoding step)
"""

from sklearn.preprocessing import LabelEncoder
import pickle

print("="*50)
print("🏷️ LABEL ENCODING")
print("="*50)

# Dictionary to store encoders for later use
encoders = {}
df_encoded = df.copy()

# Columns for Label Encoding
label_encode_cols = ['gender', 'internet_access', 'sleep_quality',
                     'facility_rating', 'exam_difficulty']

print("\n📝 Encoding these columns with LabelEncoder:")
print("-" * 40)

for col in label_encode_cols:
    # Create and fit encoder
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df[col])

    # Store encoder
    encoders[f'label_{col}'] = le

    # Print mapping
    print(f"\n{col.upper()}:")
    print(f"  Unique values: {df[col].unique().tolist()}")
    print(f"  Encoded as: {le.transform(le.classes_).tolist()}")
    print(f"  Mapping: {dict(zip(le.classes_, le.transform(le.classes_)))}")

print("\n" + "="*50)
print("✅ Label Encoding Complete")
print("="*50)

# Show sample after encoding
print("\n📋 Sample data after Label Encoding (first 5 rows):")
print(df_encoded[label_encode_cols].head())

==================================================
🏷️ LABEL ENCODING
==================================================

📝 Encoding these columns with LabelEncoder:
----------------------------------------

GENDER:
  Unique values: ['female', 'other', 'male']
  Encoded as: [0, 1, 2]
  Mapping: {'female': np.int64(0), 'male': np.int64(1), 'other': np.int64(2)}

INTERNET_ACCESS:
  Unique values: ['no', 'yes']
  Encoded as: [0, 1]
  Mapping: {'no': np.int64(0), 'yes': np.int64(1)}

SLEEP_QUALITY:
  Unique values: ['average', 'poor', 'good']
  Encoded as: [0, 1, 2]
  Mapping: {'average': np.int64(0), 'good': np.int64(1), 'poor': np.int64(2)}

FACILITY_RATING:
  Unique values: ['low', 'medium', 'high']
  Encoded as: [0, 1, 2]
  Mapping: {'high': np.int64(0), 'low': np.int64(1), 'medium': np.int64(2)}

EXAM_DIFFICULTY:
  Unique values: ['easy', 'moderate', 'hard']
  Encoded as: [0, 1, 2]
  Mapping: {'easy': np.int64(0), 'hard': np.int64(1), 'moderate': np.int64(2)}

==================================================
✅ Label Encoding Complete
==================================================

📋 Sample data after Label Encoding (first 5 rows):
   gender  internet_access  sleep_quality  facility_rating  exam_difficulty
0       0                0              0                1                0
1       2                1              2                2                2
2       0                1              2                0                2
3       1                1              0                0                2
4       1                1              1                0                0

In [113]:
df

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,student_performance
0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.300,Excellent
1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.700,Poor
2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.000,Excellent
3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.900,Good
4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.000,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,18,female,b.tech,4.86,70.7,yes,4.1,good,mixed,high,moderate,69.500,Good
629996,21,female,ba,7.08,54.4,yes,4.5,average,mixed,low,moderate,78.900,Excellent
629997,24,male,bca,0.64,44.2,yes,4.3,poor,online videos,low,moderate,19.599,Poor
629998,20,male,b.com,1.54,75.1,yes,8.2,average,group study,high,moderate,59.100,Average
629999,18,other,b.tech,3.94,75.3,yes,5.8,poor,online videos,low,easy,37.200,Poor

CELL 2: One-Hot Encoding

In [114]:
"""
📌 TASK 2.2: One-Hot Encoding
-----------------------------------------------------------
KYA: Bache hue categorical columns ko One-Hot Encoding se convert kar rahe hain
      (course, study_method, student_performance)
KYUN: In columns mein unique values zyada hain (4+), isliye One-Hot Encoding better hai
      Har unique value ke liye naya column banega
KAUNSA KAAM: Feature Encoding (Dusra encoding step)
"""

print("="*50)
print("🔄 ONE-HOT ENCODING")
print("="*50)

# Columns for One-Hot Encoding
onehot_encode_cols = ['course', 'study_method', 'student_performance']

print(f"\n📝 Encoding these columns with One-Hot Encoding:")
print(f"   {onehot_encode_cols}")
print("-" * 50)

# Check unique values before encoding
for col in onehot_encode_cols:
    unique_vals = df_encoded[col].unique()
    print(f"\n{col.upper()}:")
    print(f"  Unique values: {unique_vals}")
    print(f"  Total categories: {len(unique_vals)}")

# Apply One-Hot Encoding
print("\n" + "="*50)
print("Applying One-Hot Encoding...")
print("="*50)

# Get dummies (One-Hot Encoding)
df_encoded = pd.get_dummies(df_encoded, columns=onehot_encode_cols, prefix=onehot_encode_cols)

print("\n✅ One-Hot Encoding Complete!")

# Show new columns created
new_cols = [col for col in df_encoded.columns if any(x in col for x in onehot_encode_cols)]
print(f"\n📊 New columns created ({len(new_cols)} total):")
print("-" * 50)
for col in new_cols[:10]:  # Show first 10
    print(f"  • {col}")

print("\n" + "="*50)
print(f"📈 Dataset shape after encoding: {df_encoded.shape}")
print(f"   Rows: {df_encoded.shape[0]:,}")
print(f"   Columns: {df_encoded.shape[1]}")
print("="*50)

# Show sample of encoded data
print("\n📋 Sample data after One-Hot Encoding (first 3 rows, selected columns):")
sample_cols = ['gender', 'age', 'study_hours'] + new_cols[:5]
print(df_encoded[sample_cols].head(3))

==================================================
🔄 ONE-HOT ENCODING
==================================================

📝 Encoding these columns with One-Hot Encoding:
   ['course', 'study_method', 'student_performance']
--------------------------------------------------

COURSE:
  Unique values: ['b.sc' 'diploma' 'bca' 'b.com' 'ba' 'bba' 'b.tech']
  Total categories: 7

STUDY_METHOD:
  Unique values: ['online videos' 'self-study' 'coaching' 'group study' 'mixed']
  Total categories: 5

STUDENT_PERFORMANCE:
  Unique values: ['Excellent' 'Poor' 'Good' 'Average']
  Total categories: 4

==================================================
Applying One-Hot Encoding...
==================================================

✅ One-Hot Encoding Complete!

📊 New columns created (16 total):
--------------------------------------------------
  • course_b.com
  • course_b.sc
  • course_b.tech
  • course_ba
  • course_bba
  • course_bca
  • course_diploma
  • study_method_coaching
  • study_method_group study
  • study_method_mixed

==================================================
📈 Dataset shape after encoding: (630000, 26)
   Rows: 630,000
   Columns: 26
==================================================

📋 Sample data after One-Hot Encoding (first 3 rows, selected columns):
   gender  age  study_hours  course_b.com  course_b.sc  course_b.tech  \
0       0   21         7.91         False         True          False
1       2   18         4.95         False        False          False
2       0   20         4.68         False         True          False

   course_ba  course_bba
0      False       False
1      False       False
2      False       False

TASK 3: FEATURE SCALING
Ab numerical columns ko scale karenge.

In [115]:
"""
📌 TASK 3: Feature Scaling (StandardScaler)
-----------------------------------------------------------
KYA: Numerical columns ko scale kar rahe hain (0 ke around mean, 1 standard deviation)
KYUN: Different scales (e.g., age 18-24, study_hours 0-10) model ko confuse karte hain
      Scaling se sab columns ko equal importance milti hai
KAUNSA KAAM: Feature Scaling (Model ke liye data prepare)
"""

from sklearn.preprocessing import StandardScaler
import numpy as np

print("="*50)
print("📏 FEATURE SCALING (STANDARDSCALER)")
print("="*50)

# Numerical columns to scale
numerical_cols = ['age', 'study_hours', 'class_attendance', 'sleep_hours', 'exam_score']

print(f"\n📝 Scaling these numerical columns:")
print(f"   {numerical_cols}")
print("-" * 50)

# Show statistics before scaling
print("\n📊 Statistics BEFORE Scaling:")
print("-" * 30)
for col in numerical_cols:
    print(f"{col}:")
    print(f"  Mean = {df_encoded[col].mean():.2f}")
    print(f"  Std  = {df_encoded[col].std():.2f}")
    print(f"  Min  = {df_encoded[col].min():.2f}")
    print(f"  Max  = {df_encoded[col].max():.2f}")

# Initialize and fit scaler
scaler = StandardScaler()
df_encoded[numerical_cols] = scaler.fit_transform(df_encoded[numerical_cols])

# Store scaler for later use
encoders['scaler'] = scaler

print("\n" + "="*50)
print("✅ Scaling Complete!")
print("="*50)

# Show statistics after scaling
print("\n📊 Statistics AFTER Scaling:")
print("-" * 30)
for col in numerical_cols:
    print(f"{col}:")
    print(f"  Mean = {df_encoded[col].mean():.2f}")
    print(f"  Std  = {df_encoded[col].std():.2f}")
    print(f"  Min  = {df_encoded[col].min():.2f}")
    print(f"  Max  = {df_encoded[col].max():.2f}")

# Show sample of scaled data
print("\n" + "="*50)
print("📋 Sample data after Scaling (first 3 rows):")
print("-" * 50)
print(df_encoded[numerical_cols].head(3))

print("\n" + "="*50)
print(f"📈 Final dataset shape: {df_encoded.shape}")
print(f"   Rows: {df_encoded.shape[0]:,}")
print(f"   Columns: {df_encoded.shape[1]}")
print("="*50)

==================================================
📏 FEATURE SCALING (STANDARDSCALER)
==================================================

📝 Scaling these numerical columns:
   ['age', 'study_hours', 'class_attendance', 'sleep_hours', 'exam_score']
--------------------------------------------------

📊 Statistics BEFORE Scaling:
------------------------------
age:
  Mean = 20.55
  Std  = 2.26
  Min  = 17.00
  Max  = 24.00
study_hours:
  Mean = 4.00
  Std  = 2.36
  Min  = 0.08
  Max  = 7.91
class_attendance:
  Mean = 71.99
  Std  = 17.43
  Min  = 40.60
  Max  = 99.40
sleep_hours:
  Mean = 7.07
  Std  = 1.74
  Min  = 4.10
  Max  = 9.90
exam_score:
  Mean = 62.51
  Std  = 18.92
  Min  = 19.60
  Max  = 100.00

==================================================
✅ Scaling Complete!
==================================================

📊 Statistics AFTER Scaling:
------------------------------
age:
  Mean = 0.00
  Std  = 1.00
  Min  = -1.57
  Max  = 1.53
study_hours:
  Mean = -0.00
  Std  = 1.00
  Min  = -1.66
  Max  = 1.66
class_attendance:
  Mean = 0.00
  Std  = 1.00
  Min  = -1.80
  Max  = 1.57
sleep_hours:
  Mean = 0.00
  Std  = 1.00
  Min  = -1.70
  Max  = 1.62
exam_score:
  Mean = -0.00
  Std  = 1.00
  Min  = -2.27
  Max  = 1.98

==================================================
📋 Sample data after Scaling (first 3 rows):
--------------------------------------------------
        age  study_hours  class_attendance  sleep_hours  exam_score
0  0.200943     1.655875          1.538302    -1.245269    0.834881
1 -1.126352     0.401573          1.308814    -1.359895   -0.835586
2 -0.241488     0.287160          1.182595    -0.729454    1.929142

==================================================
📈 Final dataset shape: (630000, 26)
   Rows: 630,000
   Columns: 26
==================================================

TASK 4: TRAIN-TEST SPLIT
Ab data ko training (80%) aur testing (20%) mein divide karte hain.

In [116]:
"""
📌 TASK 4: Train-Test Split
-----------------------------------------------------------
KYA: Data ko do parts mein divide kar rahe hain:
     - Training Set (80%): Model ko train karne ke liye
     - Testing Set (20%): Model ko test karne ke liye
KYUN: Model ko unseen data par evaluate karna hota hai
      Alag data par test karenge to pata chalega ki model kitna accurate hai
KAUNSA KAAM: Final Data Preparation (Model ke liye ready)
"""

from sklearn.model_selection import train_test_split
import pickle

print("="*50)
print("✂️ TRAIN-TEST SPLIT")
print("="*50)

# Step 1: Separate Features (X) and Target (y)
# Target variable kya hai? - 'student_performance' (One-Hot encoded columns)
target_cols = [col for col in df_encoded.columns if col.startswith('student_performance_')]
print(f"\n🎯 Target columns (One-Hot encoded):")
for col in target_cols:
    print(f"   • {col}")

# For classification, we need single target column (not One-Hot)
# Convert One-Hot back to single column
target_original = df[['student_performance','exam_score']]  # Original target from before encoding
X = df_encoded.drop(columns=target_cols + ['exam_score'])  # Features (remove target columns)

y = df['student_performance']  # Target

print(f"\n📊 Features (X) shape: {X.shape}")
print(f"📊 Target (y) shape: {y.shape}")
print(f"\n📝 Features columns: {list(X.columns)}")
print(f"\n🎯 Target unique values: {y.unique()}")

# Step 2: Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,           # 20% for testing
    random_state=42,          # Reproducible results
    stratify=y               # Maintain class distribution
)

print("\n" + "="*50)
print("✅ SPLIT COMPLETE")
print("="*50)
print(f"\n📈 Training set size (80%):")
print(f"   X_train: {X_train.shape}")
print(f"   y_train: {y_train.shape}")
print(f"   Samples: {len(X_train):,}")

print(f"\n📈 Testing set size (20%):")
print(f"   X_test: {X_test.shape}")
print(f"   y_test: {y_test.shape}")
print(f"   Samples: {len(X_test):,}")

# Step 3: Check distribution
print("\n" + "="*50)
print("📊 TARGET DISTRIBUTION")
print("="*50)

print("\n📊 Original dataset:")
print(y.value_counts(normalize=True).round(3) * 100)

print("\n📊 Training set:")
print(y_train.value_counts(normalize=True).round(3) * 100)

print("\n📊 Testing set:")
print(y_test.value_counts(normalize=True).round(3) * 100)

# Step 4: Save all files for Model Training team
print("\n" + "="*50)
print("💾 SAVING FILES FOR MODEL TRAINING TEAM")
print("="*50)

# Save datasets
X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)

# Save encoders and scaler
with open('encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)

# Save feature names
with open('feature_names.pkl', 'wb') as f:
    pickle.dump(list(X.columns), f)

print("\n✅ Files saved successfully:")
print("   1. X_train.csv - Training features")
print("   2. X_test.csv - Testing features")
print("   3. y_train.csv - Training target")
print("   4. y_test.csv - Testing target")
print("   5. encoders.pkl - LabelEncoders and Scaler")
print("   6. feature_names.pkl - Feature names list")

print("\n" + "="*50)
print("🎉 TASK COMPLETE! ML-READY DATASET READY")
print("="*50)
print("\n📢 Message for Model Training Team (Ashish & Hardik):")
print("-" * 50)
print("Hi Team,")
print("Feature Engineering complete! Files ready for model training:")
print("• X_train.csv, X_test.csv - Features (26 columns)")
print("• y_train.csv, y_test.csv - Target (student_performance)")
print("• encoders.pkl - For Flask integration later")
print("\nDataset stats:")
print(f"• Training samples: {len(X_train):,}")
print(f"• Testing samples: {len(X_test):,}")
print(f"• Features: {X_train.shape[1]}")
print("\nTarget classes: Excellent, Good, Average, Poor")
print("\nPlease start model training! 🚀")

==================================================
✂️ TRAIN-TEST SPLIT
==================================================

🎯 Target columns (One-Hot encoded):
   • student_performance_Average
   • student_performance_Excellent
   • student_performance_Good
   • student_performance_Poor

📊 Features (X) shape: (630000, 21)
📊 Target (y) shape: (630000,)

📝 Features columns: ['age', 'gender', 'study_hours', 'class_attendance', 'internet_access', 'sleep_hours', 'sleep_quality', 'facility_rating', 'exam_difficulty', 'course_b.com', 'course_b.sc', 'course_b.tech', 'course_ba', 'course_bba', 'course_bca', 'course_diploma', 'study_method_coaching', 'study_method_group study', 'study_method_mixed', 'study_method_online videos', 'study_method_self-study']

🎯 Target unique values: ['Excellent' 'Poor' 'Good' 'Average']

==================================================
✅ SPLIT COMPLETE
==================================================

📈 Training set size (80%):
   X_train: (504000, 21)
   y_train: (504000,)
   Samples: 504,000

📈 Testing set size (20%):
   X_test: (126000, 21)
   y_test: (126000,)
   Samples: 126,000

==================================================
📊 TARGET DISTRIBUTION
==================================================

📊 Original dataset:
student_performance
Average      25.1
Poor         25.1
Good         25.0
Excellent    24.8
Name: proportion, dtype: float64

📊 Training set:
student_performance
Average      25.1
Poor         25.1
Good         25.0
Excellent    24.8
Name: proportion, dtype: float64

📊 Testing set:
student_performance
Average      25.1
Poor         25.1
Good         25.0
Excellent    24.8
Name: proportion, dtype: float64

==================================================
💾 SAVING FILES FOR MODEL TRAINING TEAM
==================================================

✅ Files saved successfully:
   1. X_train.csv - Training features
   2. X_test.csv - Testing features
   3. y_train.csv - Training target
   4. y_test.csv - Testing target
   5. encoders.pkl - LabelEncoders and Scaler
   6. feature_names.pkl - Feature names list

==================================================
🎉 TASK COMPLETE! ML-READY DATASET READY
==================================================

📢 Message for Model Training Team (Ashish & Hardik):
--------------------------------------------------
Hi Team,
Feature Engineering complete! Files ready for model training:
• X_train.csv, X_test.csv - Features (26 columns)
• y_train.csv, y_test.csv - Target (student_performance)
• encoders.pkl - For Flask integration later

Dataset stats:
• Training samples: 504,000
• Testing samples: 126,000
• Features: 21

Target classes: Excellent, Good, Average, Poor

Please start model training! 🚀

In [117]:
X_train

,age,gender,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,facility_rating,exam_difficulty,course_b.com,...,course_b.tech,course_ba,course_bba,course_bca,course_diploma,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
57789,1.528239,1,1.583837,0.149898,1,-0.500202,0,0,0,False,...,False,False,False,False,False,True,False,False,False,False
108847,0.643375,0,1.316874,-1.077864,1,1.448434,2,1,2,False,...,False,True,False,False,False,False,True,False,False,False
488817,1.085807,2,-1.407843,-0.659048,1,-1.073331,1,2,0,False,...,False,False,False,True,False,True,False,False,False,False
247204,-1.126352,2,0.999061,-1.479469,1,-1.417208,2,1,0,False,...,True,False,False,False,False,False,True,False,False,False
466900,1.085807,2,-1.636668,1.251442,1,-0.500202,0,1,2,False,...,True,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466401,1.528239,2,-0.412029,0.121212,1,-0.786767,0,2,1,True,...,False,False,False,False,False,False,True,False,False,False
180093,-0.683920,2,-1.183255,-1.261455,1,0.760680,0,1,2,False,...,False,False,False,True,False,True,False,False,False,False
209519,-0.683920,0,1.507562,-0.922959,1,1.620373,1,1,2,False,...,False,False,True,False,False,False,False,False,True,False
514992,1.085807,0,-1.034942,-0.504143,1,1.563060,2,0,2,True,...,False,False,False,False,False,True,False,False,False,False
249440,0.643375,1,0.850748,-0.532829,1,-0.442890,1,0,2,True,...,False,False,False,False,False,False,False,False,True,False

📂 Your Output Files:
├── X_train.csv     → Training features (504,000 × 22)
├── X_test.csv      → Testing features (126,000 × 22)
├── y_train.csv     → Training target (504,000)
├── y_test.csv      → Testing target (126,000)
├── encoders.pkl    → LabelEncoders + Scaler (for Flask)
└── feature_names.pkl → Feature names list

In [125]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

model = HistGradientBoostingClassifier(max_iter=100, learning_rate=0.1, random_state=42)


model.fit(X_train, y_train)


y_pred = model.predict(X_test)

# 4. Accuracy Check
acc = accuracy_score(y_test, y_pred)

print("\n" + "="*50)
print(f"FINAL MODEL ACCURACY: {acc*100:.2f}%")
print("="*50)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

==================================================
FINAL MODEL ACCURACY: 64.89%
==================================================

Classification Report:
              precision    recall  f1-score   support

     Average       0.54      0.52      0.53     31662
   Excellent       0.75      0.76      0.76     31261
        Good       0.54      0.55      0.54     31509
        Poor       0.76      0.77      0.77     31568

    accuracy                           0.65    126000
   macro avg       0.65      0.65      0.65    126000
weighted avg       0.65      0.65      0.65    126000

In [127]:
import pickle

with open("lovepreet_model.pkl","wb") as f:
    pickle.dump(model,f)

In [120]:
print(df.corr(numeric_only=True))

                       age  study_hours  class_attendance  sleep_hours  \
age               1.000000     0.007545          0.005628     0.005864
study_hours       0.007545     1.000000          0.087617     0.042491
class_attendance  0.005628     0.087617          1.000000     0.029263
sleep_hours       0.005864     0.042491          0.029263     1.000000
exam_score        0.010472     0.762267          0.360954     0.167410

                  exam_score
age                 0.010472
study_hours         0.762267
class_attendance    0.360954
sleep_hours         0.167410
exam_score          1.000000

In [121]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [122]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_split=5,
    random_state=42
)

model.fit(X_train_scaled, y_train)

RandomForestClassifier(max_depth=12, min_samples_split=5, n_estimators=300,
                       random_state=42)

In [123]:
y_pred = model.predict(X_test_scaled)

In [124]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6358492063492064